### PR TITLE
Add linux support

### PR DESCRIPTION
**Pull request by mtricht**
Caveats:

- No system tray icon. We're adding a configuration window later, so for now you'll have to directly edit the config file found in `~/config/Lunaris/`
- Stash scroll does not work. X11 does not allow event consumption.
- Macros can't be on an hotkey that also use a skill or opens a in-game window. Also due to X11 not being able to consume events.
- Path of Exile has to be on your main screen.
- The background is grey as transparency is not supported.
- The macros will always listen to the hotkeys, even when Path of Exile is not focused. If anyone is willing to contribute the X11 native calls, that'd be nice.

Only tested on Manjaro GNOME.

### CODE REVIEW

**Comment by thorsten-passfeld** [comment]
Okay, so I was unsure how to actually test this properly, so I checked out the branch and tried to run the shell script, but the binaries it tried to access weren't there. So I just built the project in Netbeans and ran it. The systray icon appeared and I was able to configure the league, etc. The design just looked more like Windows XP there but that's totally fine and can definitely improved in the future.

Ingame, I tried out the various shortcuts from the front page of the repository. For some reason, F5 doesn't write /hideout in the chat, but it writes 7hideout instead.
Should be a quick fix, I'd assume. The other shortcuts like "alt + W" or "alt + D" didn't work yet. Maybe I'm missing something? Nothing appeared, nor did it open my browser.

I'm using Manjaro KDE.

**Comment by mtricht** [comment]
@thorsten-passfeld thanks, I'll install KDE and test things out

**Comment by mtricht** [comment]
@thorsten-passfeld I have added some debug statements, could you retry and post the output from the console?

Also, to double check:
- Are you playing in fullscreen? It has to be windowed or windowed fullscreen.
- Is your keyboard layout German? Sadly the AWT `Robot` class we use for typing has very poor support for multiple keyboard layouts. We circumvent this in Windows by using alt codes, but those don't exist on Linux. So I'm not sure yet how to solve this one.

**Comment by thorsten-passfeld** [comment]
I'm playing in windowed fullscreen. Yeah, my keyboard is German.

Good thing you asked me to test it out again. I randomly had my Chromium browser open and pressing alt + D (or Q, not sure) actually opened a relevant search for my item in Chromium, but only when it was open already.

The rest still behaved the same. This is what your logger outputs:

18:42:52.687 DEBUG dev.tricht.lunaris.Lunaris - Ready!
18:45:45.513 DEBUG dev.tricht.lunaris.listeners.ItemPriceListener - Getting item price.
18:45:45.513 DEBUG dev.tricht.lunaris.item.ItemGrabber - Pressing ctrl+c
18:45:45.618 DEBUG dev.tricht.lunaris.item.ItemGrabber - Grabbing clipboard
18:45:45.703 DEBUG dev.tricht.lunaris.item.ItemGrabber - Clipboard is not empty
18:45:45.737 DEBUG dev.tricht.lunaris.com.pathofexile.PathOfExileAPI - Affix 22% increased Spell Damage found as explicit.stat_2974417149
18:45:45.737 DEBUG dev.tricht.lunaris.com.pathofexile.PathOfExileAPI - Affix +32 to maximum Mana found as explicit.stat_1050105434
18:45:45.737 DEBUG dev.tricht.lunaris.com.pathofexile.PathOfExileAPI - Affix 58% increased Mana Regeneration Rate found as explicit.stat_789117908
18:45:49.483 DEBUG dev.tricht.lunaris.item.ItemGrabber - Pressing ctrl+c
18:45:49.586 DEBUG dev.tricht.lunaris.item.ItemGrabber - Grabbing clipboard
18:45:49.679 DEBUG dev.tricht.lunaris.item.ItemGrabber - Clipboard is not empty
18:45:52.282 DEBUG dev.tricht.lunaris.listeners.ItemPriceListener - Getting item price.

(java:21808): GLib-GIO-WARNING **: 18:45:52.283: /etc/xdg/kde-mimeapps.list contains a [Added Associations] group, but it is not permitted here.  Only the non-desktop-specific mimeapps.list file may add or remove associations.
18:46:04.585 DEBUG dev.tricht.lunaris.listeners.ItemPriceListener - Getting item price.
18:46:04.585 DEBUG dev.tricht.lunaris.listeners.ItemPriceListener - pathofexile.com/trade
18:46:04.585 DEBUG dev.tricht.lunaris.item.ItemGrabber - Pressing ctrl+c
18:46:04.696 DEBUG dev.tricht.lunaris.item.ItemGrabber - Grabbing clipboard
18:46:04.701 DEBUG dev.tricht.lunaris.item.ItemGrabber - Clipboard is empty.
18:46:04.702 DEBUG dev.tricht.lunaris.listeners.ItemPriceListener - No item selected.
18:46:21.198 DEBUG dev.tricht.lunaris.listeners.ItemPriceListener - Getting item price.
18:46:21.198 DEBUG dev.tricht.lunaris.listeners.ItemPriceListener - pathofexile.com/trade
18:46:21.198 DEBUG dev.tricht.lunaris.item.ItemGrabber - Pressing ctrl+c
18:46:21.305 DEBUG dev.tricht.lunaris.item.ItemGrabber - Grabbing clipboard
18:46:21.306 DEBUG dev.tricht.lunaris.item.ItemGrabber - Clipboard is empty.
18:46:21.307 DEBUG dev.tricht.lunaris.listeners.ItemPriceListener - No item selected.
18:46:26.671 DEBUG dev.tricht.lunaris.listeners.ItemPriceListener - Getting item price.
18:46:26.672 DEBUG dev.tricht.lunaris.item.ItemGrabber - Pressing ctrl+c
18:46:26.775 DEBUG dev.tricht.lunaris.item.ItemGrabber - Grabbing clipboard
18:46:26.879 DEBUG dev.tricht.lunaris.item.ItemGrabber - Clipboard is not empty
18:46:26.881 DEBUG dev.tricht.lunaris.com.pathofexile.PathOfExileAPI - Affix 22% increased Spell Damage found as explicit.stat_2974417149
18:46:26.881 DEBUG dev.tricht.lunaris.com.pathofexile.PathOfExileAPI - Affix +32 to maximum Mana found as explicit.stat_1050105434
18:46:26.881 DEBUG dev.tricht.lunaris.com.pathofexile.PathOfExileAPI - Affix 58% increased Mana Regeneration Rate found as explicit.stat_789117908
18:46:27.875 DEBUG dev.tricht.lunaris.listeners.ItemPriceListener - Getting item price.
Opening in existing browser session.
18:46:49.208 DEBUG dev.tricht.lunaris.item.ItemGrabber - Pressing ctrl+c
18:46:49.316 DEBUG dev.tricht.lunaris.item.ItemGrabber - Grabbing clipboard
18:46:49.316 DEBUG dev.tricht.lunaris.item.ItemGrabber - Clipboard is empty.

**Comment by mtricht** [comment]
@thorsten-passfeld hideout macro should now be fixed. We may have a fix for the item keybinds not working, which is unrelated to linux. Will update you later.

**Pull request merged**
